#!/usr/bin/env bash
echo "TBD"
set -x # trace commands

docker run \
  -m "300M" --memory-swap "1G" \
  -w "/usr/src/myapp" \
  -u "root"   \
  --rm \
  -it\
  --name "ufp-gradle-app" \
  -v $(pwd):/usr/src/myapp  \
  gradle:jdk8 gradle $@
