#!/usr/bin/env bash
echo "TBD"
set -x # trace commands

docker run \
  -m "1G" --memory-swap "1G" \
  -w "/usr/src/myapp" \
  --rm \
  -it\
  --name "ufp-maven-app" \
  -v "ufp-maven-repo:/root/.m2" \
  -v $(pwd):/usr/src/myapp  \
  maven:3.6-jdk-8-slim mvn $@
