#!/usr/bin/env bash
#  set -x # trace commands
docker run \
  -m "300M" --memory-swap "1G" \
  -w "/usr/src/ufp-app" \
  --rm \
  -it\
  --name "ufp-python-app" \
  -p "3000:3000" \
  -v "$(pwd):/usr/src/ufp-app" \
 python:2.7.15-alpine3.8 python $@
